version: '3'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        volumes:
            - ".:/app/"
        command: sh -c "sleep 5s && go run ."
        ports:
            - "8080:8080"
        depends_on:
            - database
        tty: True
    mock-test:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/app/"
        command: sh -c "sleep 5s && go test -coverpkg=./... -coverprofile=coverage.out ./tests/... -v"
        depends_on:
            - database
        tty: True
    database:
        image: postgres:9.6.22-alpine3.14
        restart: on-failure
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=gorm
            - POSTGRES_PASSWORD=gorm
            - POSTGRES_DB=shop-sys-db
            - DATABASE_HOST=database
        tty: True